import type { Metadata } from 'next';
import '../globals.css';

import { useState } from 'react';
import Sidebar from './Components/Sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className='flex h-screen overflow-hidden bg-gray-100'>
        <Sidebar />
        <div className='bg-[#FEFAEF] w-screen modal-close' id='side-body'>
          {children}
        </div>
      </body>
    </html>
  )
}
