import type { Metadata } from 'next';
import '../globals.css';
import SidebarComponent from './Components/Sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="relative flex flex-row antialiased bg-slate-100">
          <SidebarComponent />
          {children}
        </div>
      </body>
    </html>
  )
}
