import '@/app/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function LoginLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className='flex h-screen bg-gray-100'>
        <div className='bg-[#FEFAEF] w-screen'>
          {children}
        </div>
      </body>
    </html>
  )
}
